### ISSUE TITLE
`yarn test` failed at `integration/solana`

### ISSUE THREAD

**Issue by youngqqcn** [hyperledger/solang#1056]
```
...
  15) Deploy solang contract and test
       account storage too small dynamic realloc:
     Error: expect(received).rejects.toThrowError(expected)

Expected message: "account data too small for instruction"
Received message: "failed to send transaction: Transaction simulation failed: Error processing Instruction 0: account data too small for instruction"

      at Connection.sendEncodedTransaction (node_modules/@solana/web3.js/src/connection.ts:4068:13)
      at async Connection.sendRawTransaction (node_modules/@solana/web3.js/src/connection.ts:4030:20)
      at async Connection.sendTransaction (node_modules/@solana/web3.js/src/connection.ts:4018:12)
      at async sendAndConfirmTransaction (node_modules/@solana/solidity/node_modules/@solana/web3.js/src/utils/send-and-confirm-transaction.ts:31:21)
      at Object.toThrowError (node_modules/expect/build/index.js:241:20)
      at Context.<anonymous> (simple.spec.ts:362:14)
      at step (simple.spec.ts:33:23)
      at Object.next (simple.spec.ts:14:53)
      at fulfilled (simple.spec.ts:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  16) Deploy solang contract and test
       arrays in account storage:
     TypeError: Cannot read properties of undefined (reading 'numRequiredSignatures')
      at Function.populate (node_modules/@solana/web3.js/src/transaction.ts:768:24)
      at Connection.simulateTransaction (node_modules/@solana/web3.js/src/connection.ts:3897:33)
      at /data/qiyichain/solang/integration/solana/node_modules/@solana/solidity/src/logs.ts:116:37
      at Generator.next (<anonymous>)
      at /data/qiyichain/solang/integration/solana/node_modules/@solana/solidity/lib/logs.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/@solana/solidity/lib/logs.js:4:12)
      at simulateTransactionWithLogs (node_modules/@solana/solidity/lib/logs.js:97:12)
      at Contract.<anonymous> (node_modules/@solana/solidity/src/contract.ts:508:52)
      at Generator.next (<anonymous>)

```

**Comment by LucasSte** [comment]
Hi @youngqqcn, we have recently updated the typescript library to a new version (see #1058). Can you please update your repository to the latest commit and try again?
