### ISSUE TITLE
Lsp mode crashes when `--importmap` is set.

### ISSUE THREAD

**Issue by aj3423** [hyperledger/solang#1162]
**Describe the bug**
The `--importmap` doesn't work with `language-server`, it crashes. (It works fine with `compile` though.)

**To Reproduce**
1.  Solang version: v0.2.1 
2. Open command line, in any directory, type:

 `solang language-server --target solana --importmap lib=/usr/local/lib`

It crashes with error:
```
thread 'main' panicked at 'Mismatch between definition and access of `IMPORTMAP`. Could not downcast to T
ypeId { t: 1896031399542294508 }, need to downcast to TypeId { t: 15013602091056753095 }
', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.0.32/src/parser/error.rs:30:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
If I set the environment variable `RUST_BACKTRACE=full`, it shows more detail:
```
thread 'main' panicked at 'Mismatch between definition and access of `IMPORTMAP`. Could not downcast to TypeId { t: 1896031399542294508 }, need to downcast to TypeId { t: 15013602091056753095 }
', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.0.32/src/parser/error.rs:30:9
stack backtrace:
   0:     0x5623ca678871 - std::backtrace_rs::backtrace::libunwind::trace::h8217d0a8f3fd2f41
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5623ca678871 - std::backtrace_rs::backtrace::trace_unsynchronized::h308103876b3af410
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5623ca678871 - std::sys_common::backtrace::_print_fmt::hc208018c6153605e
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x5623ca678871 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf89a7ed694dfb585
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x5623ca0b9f1c - core::fmt::write::h21038c1382fe4264
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/fmt/mod.rs:1197:17
   5:     0x5623ca656ce4 - std::io::Write::write_fmt::h7dbb1c9a3c254aef
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/io/mod.rs:1672:15
   6:     0x5623ca679846 - std::sys_common::backtrace::_print::h4e8889719c9ddeb8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x5623ca679846 - std::sys_common::backtrace::print::h1506fe2cb3022667
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x5623ca679846 - std::panicking::default_hook::{{closure}}::hd9d7ce2a8a782440
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:295:22
   9:     0x5623ca67a8d7 - std::panicking::default_hook::h5b16ec25444b1b5d
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:314:9
  10:     0x5623ca67a8d7 - std::panicking::rust_panic_with_hook::hb0138cb6e6fea3e4
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:698:17
  11:     0x5623ca67a3b2 - std::panicking::begin_panic_handler::{{closure}}::h4cb67095557cd1aa
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:588:13
  12:     0x5623ca67a326 - std::sys_common::backtrace::__rust_end_short_backtrace::h2bfcac279dcdc911
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x5623ca67a2e2 - rust_begin_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
  14:     0x5623c9fa89f2 - core::panicking::panic_fmt::h1de71520faaa17d3
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
  15:     0x5623ca4d9d7b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf686efa084df59ee
  16:     0x5623ca461f1b - tokio::macros::scoped_tls::ScopedKey<T>::set::h0db72cb0b63c19af
  17:     0x5623ca4e8e0e - tokio::runtime::scheduler::current_thread::CurrentThread::block_on::hc1bfa57b58a2817b
  18:     0x5623ca02c1e1 - tokio::runtime::runtime::Runtime::block_on::h179d82f2c80d2afb
  19:     0x5623ca48f6db - solang::languageserver::start_server::h311636b0b3ff8769
  20:     0x5623ca045558 - solang::main::h7dd854d4d7ec886e
  21:     0x5623ca507603 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7e8547b2b68d4a2f
  22:     0x5623ca057186 - main
  23:     0x7f2a60c23510 - <unknown>
  24:     0x7f2a60c235c9 - __libc_start_main
  25:     0x5623ca0211be - _start
  26:                0x0 - <unknown>
```

**Comment by seanyoung** [comment]
Oops, that is a regression with the move to clap 4. I'm writing a fix now.
